---
title: "Audioreactive"
subtitle: "Generative Visual Music"
---

The purpose of this site is to collect some of what I consider to be among the most innovative examples of contemporary visual music, continuing in algorithmic form creative practices that originate in the musical avant-garde of the 1920s and 1930s, in the work of artists such as Walter Ruttmann and Oscar Fischinger. (Maybe I will post some examples of their work for comparison.) Having begun then  with glass plates, wax, and cut out pieces of paper, the convergence of the moving image with music continues today on the screens of algorithmic media; but like so many media forms, the aesthetics of these media do not come out of nowhere, but draw on a rich history. Part of the purpose of this site is to bring that history back into the present. A  century after Ruttmann or Fischinger, what new forms of visual music are today's algorithmic artists creating? **Audioreactive** sets out to answer this question.

Martin Roberts  
Seoul, July 2024  
